name: qr_ar
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

# flutter pub upgrade --major-versions
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  camera: ^0.9.4+5
  tflite_flutter: 0.9.0
  tflite_flutter_helper: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/model/object_detect/
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand/static/Quicksand-Bold.ttf
        - asset: assets/fonts/Quicksand/static/Quicksand-Light.ttf
        - asset: assets/fonts/Quicksand/static/Quicksand-Medium.ttf
        - asset: assets/fonts/Quicksand/static/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand/static/Quicksand-SemiBold.ttf
